# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main
- feature/*
variables:
  Vm_Username: $(Vm_Username)
  Vm_Passwd: $(Vm_Passwd)
  Db_Username: $(Db_Username)
  Db_Passwd: $(Db_Passwd)
pool:
  vmImage: ubuntu-latest

stages:
- stage: TerraformPlan
  jobs:
    - job: Plan
      steps:
      - task: TerraformInstaller@1
        inputs:
          terraformVersion: 'latest'
      - task: TerraformTaskV4@4
        inputs:
          provider: 'azurerm'
          command: 'init'
          backendServiceArm: 'svc-conn-to-azure'
          backendAzureRmResourceGroupName: 'tfstate'
          backendAzureRmStorageAccountName: 'tfstate24429'
          backendAzureRmContainerName: 'tfstate'
          backendAzureRmKey: 'terraform.tfstate'
      - task: TerraformTaskV4@4
        env:
          Vm_Passwd: $(Vm_Passwd) 
          Db_Passwd: $(Db_Passwd)
        inputs:
          provider: 'azurerm'
          command: 'plan'
          commandOptions: '--var azarch-vm_username=$(Vm_Username) --var azarch-vm_passwd=$(Vm_Passwd) --var db_admin_login=$(Db_Username) --var db_admin_password=$(Db_Passwd) -out $(Build.ArtifactStagingDirectory)/tfplan'
          environmentServiceNameAzureRM: 'svc-conn-to-azure'
      - task: PublishBuildArtifacts@1
        inputs:
          PathtoPublish: '$(Build.ArtifactStagingDirectory)'
          ArtifactName: 'tfplan'
          publishLocation: 'Container'
- stage:
  condition: and(succeeded(), eq(variables['Build.SourceBranch'], 'refs/heads/main'))
  dependsOn: TerraformPlan
  jobs:
  - job: Apply
    steps:
    - task: TerraformTaskV4@4
      env:
        Vm_Passwd: $(Vm_Passwd)
        Db_Passwd: $(Db_Passwd) 
      inputs:
        provider: 'azurerm'
        command: 'apply'
        commandOptions: '--var azarch-vm_username=$(Vm_Username) --var azarch-vm_passwd=$(Vm_Passwd) --var db_admin_login=$(Db_Username) --var db_admin_password=$(Db_Passwd) --auto-approve $(Build.ArtifactStagingDirectory)/tfplan'
        environmentServiceNameAzureRM: 'svc-conn-to-azure'



