# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main
- feature/*
pool:
  vmImage: ubuntu-latest

stages:
- stage: TerraformPlan
  jobs:
    - job: Plan
      steps:
      - task: TerraformInstaller@1
        inputs:
          terraformVersion: 'latest'
      - task: TerraformTaskV4@4
        inputs:
          provider: 'azurerm'
          command: 'init'
          backendServiceArm: 'svc-conn-to-azure'
          backendAzureRmResourceGroupName: 'tfstate'
          backendAzureRmStorageAccountName: 'tfstate24429'
          backendAzureRmContainerName: 'tfstate'
          backendAzureRmKey: 'terraform.tfstate'
      - task: TerraformTaskV4@4
        inputs:
          provider: 'azurerm'
          command: 'plan'
          commandOptions: '-out $(Build.ArtifactStagingDirectory)/'
          environmentServiceNameAzureRM: 'svc-conn-to-azure'
      - task: PublishBuildArtifacts@1
        inputs:
          PathtoPublish: '$(Build.ArtifactStagingDirectory)'
          ArtifactName: 'tfplan'
          publishLocation: 'Container'
- stage:
  condition: and(succeeded(), eq(variables['Build.SourceBranch'], 'refs/heads/main'))
  dependsOn: TerraformPlan
  jobs:
  - job: Apply
    steps:
    - task: TerraformTaskV4@4
      inputs:
        provider: 'azurerm'
        command: 'apply'
        commandOptions: '$(Build.ArtifactStagingDirectory)/tfplan'
        environmentServiceNameAzureRM: 'svc-conn-to-azure'



